
-----create database library
CREATE TABLE Books
(
    BookID INT GENERATED BY DEFAULT on NULL AS IDENTITY,
    BookName VARCHAR2(100) NOT NULL,
    Author VARCHAR2(50) NOT NULL,
    BookYear INT,
    ISBN VARCHAR2(13),
    Publisher VARCHAR2(70),
    CONSTRAINT  PK_Books_BookID
    PRIMARY KEY (BookID)
);



CREATE TABLE Members
(
    MemberID INT GENERATED BY DEFAULT on NULL AS IDENTITY,
    FirstName VARCHAR2(40) NOT NULL,
    LastName VARCHAR2(40) NOT NULL,
    Email VARCHAR2(60) UNIQUE,
    PhoneNumber VARCHAR2(9),
    CONSTRAINT PK_Members_MemberID
    PRIMARY KEY (MemberID)
);


CREATE TABLE Staff
(
    StaffID INT GENERATED BY DEFAULT on NULL AS IDENTITY,
    FirstName VARCHAR2(40) NOT NULL,
    LastName VARCHAR2(40) NOT NULL,
    Position VARCHAR2(60),
    Email VARCHAR2(60),
    CONSTRAINT PK_Staff_StaffID
    PRIMARY KEY (StaffID)
);

CREATE TABLE Loans
(
    LoanID INT GENERATED BY DEFAULT on NULL AS IDENTITY,
    BookID INT NOT NULL,
    MemberID INT NOT NULL,
    DateFrom DATE NOT NULL,
    DueDate  DATE NOT NULL,
    ReturnDate Date,
    Returned char(1),
    CONSTRAINT PK_Loans_LoanID
    PRIMARY KEY (LoanID),
    CONSTRAINT FK_Loans_BookID
    FOREIGN KEY (BookID) REFERENCES Books (BookID),
    CONSTRAINT FK_Loans_MemberID
    FOREIGN KEY (MemberID) REFERENCES Members (MemberID),
    CONSTRAINT const_returned CHECK (Returned IN ('1','0'))
);


ALTER TABLE LOANS
ADD STAFFID INT;


ALTER TABLE LOANS
ADD CONSTRAINT FK_Loans_StaffID FOREIGN KEY (StaffID) 
REFERENCES Staff (StaffID);