

CREATE OR REPLACE VIEW view_Activeloans AS
SELECT L.BOOKID, B.BOOKNAME, L.MEMBERID, M.FIRSTNAME, M.LASTNAME, L.DATEFROM, L.DUEDATE
FROM LOANS L
INNER JOIN BOOKS B ON B.BOOKID = L.BOOKID
INNER JOIN MEMBERS M ON M.MEMBERID = L.MEMBERID
WHERE L.RETURNED = '0';