
CREATE OR REPLACE VIEW view_OverdueLoans AS
SELECT l.BOOKID, l.DATEFROM, l.DUEDATE, b.BOOKNAME, m.FIRSTNAME, m.LASTNAME
FROM LOANS l
INNER JOIN BOOKS b ON l.BOOKID = b.BOOKID
INNER JOIN MEMBERS m ON l.MEMBERID = m.MEMBERID
WHERE l.DueDate < SYSDATE AND l.RETURNED = '0';
