
CREATE OR REPLACE VIEW view_PopularBooks AS
SELECT b.BOOKID, b.BOOKNAME, b.AUTHOR, b.BOOKYEAR, COUNT(l.BOOKID) AS TOTAL_LOANS
FROM LOANS l
INNER JOIN BOOKS b on l.BOOKID = b.BOOKID
GROUP BY b.BOOKNAME, b.AUTHOR, b.BOOKYEAR
ORDER BY TOTAL_LOANS DESC, b.BOOKNAME;


